spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.81.32.32:3306/bsbdj?useUnicode=true
    username: root
    password: nicai
    #utf8 与utf8mb4的区别。
    #1-4个字节， 1~保存数字 字母   2~3保存世界的各种语言 4~特殊符号
    #mysql中默认指定的utf-8最多只包含了3个字节。4个字节的时候会抛出一个异常，InCorrect String value 无法保存4个字节
    #在评论中包含了emoji表情符号
    #为了解决这个4个字节的问题，我们需要设置两个地方：
    #1.character_set_server与其他字符集都是utf8mb4
    #2.需要设置Tomcat 连接启动的初始化sql，注意 jdbc字符串增加 ?useUnicode=true
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  thymeleaf:
    #取消thymeleaf缓存，让页面热部署
    cache: true
logging:
  file: /usr/local/logs/bsbdj.log
server:
  port: 9012

